const fs = require('fs');
const path = require('path');
const { withDangerousMod } = require('expo/config-plugins');

const BUNDLE_SCRIPT_OLD =
  '`\\"$NODE_BINARY\\" --print \\"require(\'path\').dirname(require.resolve(\'react-native/package.json\')) + \'/scripts/react-native-xcode.sh\'\\"`\\n\\n';

const BUNDLE_SCRIPT_NEW =
  'RN_XCODE_SCRIPT=\\"$(\\"$NODE_BINARY\\" --print \\"require(\'path\').dirname(require.resolve(\'react-native/package.json\')) + \'/scripts/react-native-xcode.sh\'\\")\\"\\n/bin/sh \\"$RN_XCODE_SCRIPT\\"\\n\\n';

const PODFILE_POST_INSTALL_MARKER = '# @saomiguel-hub/ios-build-fixes';

function findPbxproj(iosDir) {
  if (!fs.existsSync(iosDir)) return null;
  const entries = fs.readdirSync(iosDir);
  const xcodeproj = entries.find((name) => name.endsWith('.xcodeproj'));
  if (!xcodeproj) return null;
  return path.join(iosDir, xcodeproj, 'project.pbxproj');
}

function patchBundleScript(pbxContents) {
  if (pbxContents.includes('RN_XCODE_SCRIPT')) {
    return pbxContents;
  }
  if (!pbxContents.includes(BUNDLE_SCRIPT_OLD)) {
    return pbxContents;
  }
  return pbxContents.replace(BUNDLE_SCRIPT_OLD, BUNDLE_SCRIPT_NEW);
}

function patchPodfile(podfileContents) {
  if (podfileContents.includes(PODFILE_POST_INSTALL_MARKER)) {
    return podfileContents;
  }
  const snippet = `
    ${PODFILE_POST_INSTALL_MARKER}
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_configuration|
        build_configuration.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end`;

  const needle = 'react_native_post_install(\n      installer,\n      config[:reactNativePath],\n      :mac_catalyst_enabled => false,\n      :ccache_enabled => ccache_enabled?(podfile_properties),\n    )';
  if (!podfileContents.includes(needle)) {
    return podfileContents;
  }
  return podfileContents.replace(needle, `${needle}${snippet}`);
}

function writeXcodeEnvLocal(iosDir, projectRoot) {
  const envLocalPath = path.join(iosDir, '.xcode.env.local');
  const nodeBinary = process.env.NODE_BINARY || process.execPath;
  const body = [
    '# Generated by plugins/withIosBuildFixes.js — required when the project path contains spaces.',
    `export NODE_BINARY="${nodeBinary}"`,
    `export PROJECT_ROOT="${projectRoot}"`,
    '',
  ].join('\n');
  fs.writeFileSync(envLocalPath, body);
}

/** @type {import('expo/config-plugins').ConfigPlugin} */
function withIosBuildFixes(config) {
  return withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const projectRoot = cfg.modRequest.projectRoot;
      const iosDir = path.join(projectRoot, 'ios');

      const pbxPath = findPbxproj(iosDir);
      if (pbxPath) {
        const next = patchBundleScript(fs.readFileSync(pbxPath, 'utf8'));
        fs.writeFileSync(pbxPath, next);
      }

      const podfilePath = path.join(iosDir, 'Podfile');
      if (fs.existsSync(podfilePath)) {
        const next = patchPodfile(fs.readFileSync(podfilePath, 'utf8'));
        fs.writeFileSync(podfilePath, next);
      }

      if (fs.existsSync(iosDir)) {
        writeXcodeEnvLocal(iosDir, projectRoot);
      }

      return cfg;
    },
  ]);
}

module.exports = withIosBuildFixes;
