const fs = require('fs');
const path = require('path');
const { withDangerousMod } = require('expo/config-plugins');

const BUNDLE_SCRIPT_OLD =
  '`\\"$NODE_BINARY\\" --print \\"require(\'path\').dirname(require.resolve(\'react-native/package.json\')) + \'/scripts/react-native-xcode.sh\'\\"`\\n\\n';

const BUNDLE_SCRIPT_NEW =
  'RN_XCODE_SCRIPT=\\"$(\\"$NODE_BINARY\\" --print \\"require(\'path\').dirname(require.resolve(\'react-native/package.json\')) + \'/scripts/react-native-xcode.sh\'\\")\\"\\n/bin/sh \\"$RN_XCODE_SCRIPT\\"\\n\\n';

const PODFILE_POST_INSTALL_MARKER = '# @saomiguel-hub/ios-build-fixes';
const EXCONSTANTS_FIX_MARKER = '# @saomiguel-hub/exconstants-spaces-fix';

const EXCONSTANTS_SCRIPT_OLD =
  'bash -l -c \\"$PODS_TARGET_SRCROOT/../scripts/get-app-config-ios.sh\\"';
const EXCONSTANTS_SCRIPT_NEW =
  'bash -l \\"$PODS_TARGET_SRCROOT/../scripts/get-app-config-ios.sh\\"';

function findPbxproj(iosDir) {
  if (!fs.existsSync(iosDir)) return null;
  const entries = fs.readdirSync(iosDir);
  const xcodeproj = entries.find((name) => name.endsWith('.xcodeproj'));
  if (!xcodeproj) return null;
  return path.join(iosDir, xcodeproj, 'project.pbxproj');
}

function findPodsPbxproj(iosDir) {
  const podsPbx = path.join(iosDir, 'Pods', 'Pods.xcodeproj', 'project.pbxproj');
  return fs.existsSync(podsPbx) ? podsPbx : null;
}

/** EXConstants uses `bash -l -c "$SCRIPT"` which breaks when PROJECT_ROOT has spaces. */
function patchExConstantsAppConfigScript(pbxContents) {
  if (!pbxContents.includes(EXCONSTANTS_SCRIPT_OLD)) {
    return pbxContents;
  }
  return pbxContents.replaceAll(EXCONSTANTS_SCRIPT_OLD, EXCONSTANTS_SCRIPT_NEW);
}

function patchBundleScript(pbxContents) {
  if (pbxContents.includes('RN_XCODE_SCRIPT')) {
    return pbxContents;
  }
  if (!pbxContents.includes(BUNDLE_SCRIPT_OLD)) {
    return pbxContents;
  }
  return pbxContents.replace(BUNDLE_SCRIPT_OLD, BUNDLE_SCRIPT_NEW);
}

function patchPodfile(podfileContents) {
  if (podfileContents.includes(PODFILE_POST_INSTALL_MARKER)) {
    return podfileContents;
  }
  const snippet = `
    ${PODFILE_POST_INSTALL_MARKER}
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_configuration|
        build_configuration.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end`;

  const needle = 'react_native_post_install(\n      installer,\n      config[:reactNativePath],\n      :mac_catalyst_enabled => false,\n      :ccache_enabled => ccache_enabled?(podfile_properties),\n    )';
  if (!podfileContents.includes(needle)) {
    return podfileContents;
  }
  return podfileContents.replace(needle, `${needle}${snippet}`);
}

function patchPodfileExConstants(podfileContents) {
  if (podfileContents.includes(EXCONSTANTS_FIX_MARKER)) {
    return podfileContents;
  }

  const snippet = `
    ${EXCONSTANTS_FIX_MARKER}
    installer.pods_project.targets.each do |target|
      next unless target.name == 'EXConstants'
      target.shell_script_build_phases.each do |phase|
        script = phase.shell_script
        next unless script&.include?('get-app-config-ios.sh')
        broken = 'bash -l -c "$PODS_TARGET_SRCROOT/../scripts/get-app-config-ios.sh"'
        fixed = 'bash -l "$PODS_TARGET_SRCROOT/../scripts/get-app-config-ios.sh"'
        phase.shell_script = script.gsub(broken, fixed) if script.include?(broken)
      end
    end`;

  const anchor = `    ${PODFILE_POST_INSTALL_MARKER}
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_configuration|
        build_configuration.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end`;

  if (!podfileContents.includes(anchor)) {
    return podfileContents;
  }
  return podfileContents.replace(anchor, `${anchor}${snippet}`);
}

function writeXcodeEnvLocal(iosDir, projectRoot) {
  const envLocalPath = path.join(iosDir, '.xcode.env.local');
  const nodeBinary = process.env.NODE_BINARY || process.execPath;
  const body = [
    '# Generated by plugins/withIosBuildFixes.js — required when the project path contains spaces.',
    `export NODE_BINARY="${nodeBinary}"`,
    `export PROJECT_ROOT="${projectRoot}"`,
    '',
  ].join('\n');
  fs.writeFileSync(envLocalPath, body);
}

/** @type {import('expo/config-plugins').ConfigPlugin} */
function withIosBuildFixes(config) {
  return withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const projectRoot = cfg.modRequest.projectRoot;
      const iosDir = path.join(projectRoot, 'ios');

      const pbxPath = findPbxproj(iosDir);
      if (pbxPath) {
        const next = patchBundleScript(fs.readFileSync(pbxPath, 'utf8'));
        fs.writeFileSync(pbxPath, next);
      }

      const podfilePath = path.join(iosDir, 'Podfile');
      if (fs.existsSync(podfilePath)) {
        let podfile = fs.readFileSync(podfilePath, 'utf8');
        podfile = patchPodfile(podfile);
        podfile = patchPodfileExConstants(podfile);
        fs.writeFileSync(podfilePath, podfile);
      }

      const podsPbxPath = findPodsPbxproj(iosDir);
      if (podsPbxPath) {
        const next = patchExConstantsAppConfigScript(fs.readFileSync(podsPbxPath, 'utf8'));
        fs.writeFileSync(podsPbxPath, next);
      }

      if (fs.existsSync(iosDir)) {
        writeXcodeEnvLocal(iosDir, projectRoot);
      }

      return cfg;
    },
  ]);
}

module.exports = withIosBuildFixes;
