/** Moved to `features/live-tracking/lib/liveVehicleSheetLayout`. */
import {
  LIVE_ETA_ROW_HEIGHT,
  LIVE_FLEET_BAR_COMPACT_MAX_HEIGHT,
  LIVE_FLEET_BAR_HEIGHT,
  LIVE_FLEET_BAR_MAX_HEIGHT,
  LIVE_FLEET_BAR_OVERVIEW_BOTTOM_INSET,
  LIVE_VEHICLE_SHEET_HEIGHT_RATIO,
} from '@/features/live-tracking/lib/liveVehicleSheetLayout';

export const MINIBUS_LIVE_VEHICLE_SHEET_HEIGHT_RATIO = LIVE_VEHICLE_SHEET_HEIGHT_RATIO;
export const MINIBUS_LIVE_ETA_ROW_HEIGHT = LIVE_ETA_ROW_HEIGHT;
export const MINIBUS_LIVE_FLEET_BAR_HEIGHT = LIVE_FLEET_BAR_HEIGHT;
export const MINIBUS_LIVE_FLEET_BAR_MAX_HEIGHT = LIVE_FLEET_BAR_MAX_HEIGHT;
export const MINIBUS_LIVE_FLEET_BAR_COMPACT_MAX_HEIGHT = LIVE_FLEET_BAR_COMPACT_MAX_HEIGHT;
export const MINIBUS_LIVE_FLEET_BAR_OVERVIEW_BOTTOM_INSET = LIVE_FLEET_BAR_OVERVIEW_BOTTOM_INSET;
